image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_IMAGE_VERSION}

.build:
  stage: build
  tags:
    - docker-prod
  script:
    - $CI_PROJECT_DIR/scripts/linux/build.sh
    paths:
      - ${ARTIFACT}
    reports:
      junit: "*.xml"

build_psv:
  extends: .build
  #only:
    #- /^OLPEDGE-.*$/
