image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_IMAGE_VERSION}

.build:
  stage: build
  tags:
  - docker-prod
  script:
  - $CI_PROJECT_DIR/scripts/linux/gitlab_build.sh
  - $CI_PROJECT_DIR/scripts/linux/gitlab_test.sh
#  artifacts:
#    paths:
#      - ${ARTIFACT}
#    reports:
#      junit: "*.xml"

build_sv:
  extends: .build
  #only:
    #- /^OLPEDGE-.*$/
